### ISSUE TITLE
Dual solve logic optimization

### ISSUE THREAD

**Issue by MysteryPancake** [savant117/avbd-demo2d#10]
While [rewriting this in Houdini](https://github.com/MysteryPancake/Houdini-VBD), I found an optimization that preserves the dual solve logic, but moves it to the primal solve instead.
This results in 2x better performance in OpenCL, because it avoids enqueuing another kernel for dual solving.

The idea is to wait until all bodies attached to a force have been updated, then dual solve that force.
Since all bodies finish moving the C variable is correct, so the logic is identical.

This involves adding a counter to each force, then incrementing the counter using `atomic_add()`.
Each time a body updates, the counters of all attached forces are incremented.
Once a force's counter equals the number of attached bodies, it's safe to dual solve that force.

For example, say you have 2 bodies connected by a spring constraint:
```
Spring force counter = 0

Body 1 updates:
Spring force counter++

Body 2 updates:
Spring force counter++

Spring force counter (2) == Number of attached bodies (2)
Safe to dual solve
```

Hopefully this makes sense. Thanks for reading!

**Comment by MysteryPancake** [comment]
Note I'm not sure if this applies to collisions, but it applies to the simple case of bodies connected by constraints.

**Comment by savant117** [comment]
This is a great idea - I probably won't make that update to this repository in order to keep the code matching the paper as closely as possible, but for anyone implementing this (especially on the GPU), I fully endorse this optimization!

Excellent work with the Houdini implementation by the way - exciting to see this work being implemented!

**Comment by savant117** [comment]
I didn't check your implementation, but only thing I'd keep in mind with this optimization is to make sure the constraint error C is recomputed using the updated body positions - don't reuse the same C that was used to update the body during it's update

**Comment by MysteryPancake** [comment]
Yeah C is recomputed now. Previously I tried to reuse it, but it caused problems with hard constraints exploding :(

**Comment by MysteryPancake** [comment]
> exciting to see this work being implemented!

Mine is still very early in most areas, still lacks proper support for anything with 6 DOF (like rotation)

If you're interested, they also used stuff from AVBD in the new [Otis solver](http://www.sidefx.com/docs/houdini/nodes/sop/otissolver.html) in Houdini 21. This includes something inspired by hard constraints, named "Adaptive Stiffness" in Otis

**Comment by Expexium** [comment]
Im really curious how did you get a 2x performance boost, or its only applicable to a GPU solver? Here are the performance results of my 6 DoF cpu solver, dual update barely has any impact

<img width="1029" height="131" alt="Image" src="https://github.com/user-attachments/assets/50cfc978-88c1-463a-84e6-24a64b3215c3" />

**Comment by MysteryPancake** [comment]
The lag was actually due to a bug in Houdini with the way it runs kernels. It used to be over 10x slower in some cases, but this has been fixed in Houdini 21.

| Houdini 20.5 | Houdini 21 |
| --- | --- |
| <img width="386" height="38" alt="Image" src="https://github.com/user-attachments/assets/2998b914-3403-438d-9140-84420c94817e" /> | <img width="386" height="38" alt="Image" src="https://github.com/user-attachments/assets/db65e207-7d97-4ee0-a091-ea3b2de3e031" /> |

Also I found in rare cases, my method above stops being thread safe. Workitems may still access C even after they should be finished. For this reason, I don't recommend using this method anymore.

**Comment by MysteryPancake** [comment]
> Im really curious how did you get a 2x performance boost, or its only applicable to a GPU solver? Here are the performance results of my 6 DoF cpu solver, dual update barely has any impact

This varies depending on the number of connections.
Primal depends on the number of bodies, and dual depends on the number of connections (and collisions).

I was worried about AVBD since it seems it would be slower than all existing methods:
- XPBD uses dual updates only.
- VBD uses primal updates only.
- AVBD uses both primal and dual updates. This means roughly double the number of workitems.

I thought the performance would be 2x slower for this reason, but it's not too bad in practice.

**Comment by Expexium** [comment]
> XPBD uses dual updates only. VBD uses primal updates only. AVBD uses both primal and dual updates. This means roughly double the number of workitems.

The main performance issue is still the primal update for me, i removed hessians completely and did all the optimizations i couldve even possibley think of honestly. With my code i get such results, which is kinda usable, and I will actually use this solver in the actual production, These are 150 ragdolls piled on top one another (1650 rigid bodies, like 1500 joints, 1650 world manifolds, and an unknown amount of joints between the rigids themselves, but since theyre piled up its a pretty decent amount).

I will try to figure out some further optimization to the primal update, but i have no clue how yet. Thinking of somehow getting rid of the 6x6 matrix, since this thing is extremely expensive. 

<img width="619" height="647" alt="Image" src="https://github.com/user-attachments/assets/5d8c86e4-3964-483e-92c2-9ce6a91a5985" />

<img width="1027" height="129" alt="Image" src="https://github.com/user-attachments/assets/b2bdaa15-327a-4b07-9c1e-7ba474596a47" />

**Comment by MysteryPancake** [comment]
> The main performance issue is still the primal update for me, i removed hessians completely

It's not possible to remove hessians from AVBD or VBD, as both of these methods are built around hessians.
In the code above, `lhs` is the accumulated hessian and `rhs` is the accumulated force gradient.
These are more clearly labelled in the [original VBD codebase](https://github.com/AnkaChan/Gaia).

The colors loop above should also be run in parallel to match the paper.

If you want to avoid hessians I'd suggest using XPBD. It's quite a lot faster since it only uses dual updates.

**Comment by Expexium** [comment]
> The colors loop above should also be run in parallel to match the paper.

> If you want to avoid hessians I'd suggest using XPBD. It's quite a lot faster since it only uses dual updates.

Thanks for the suggestion, ill definetly switch to PBD or XPBD if the current solver's performance wont be sufficient.

And about the parallel colors loop, how is that going to work? Sorry Im kinda desperate for any info here... Wont we just end up with a Jacobi method? I really have no clue. I was coding my loop according to this:

<img width="352" height="576" alt="Image" src="https://github.com/user-attachments/assets/a2aea9cb-088d-4740-967e-82e5e881067a" />

**Comment by MysteryPancake** [comment]
You can refer to the [original VBD codebase](https://github.com/AnkaChan/Gaia) for the most detailed and complete version of VBD. AVBD is an extension on top of this. It mainly adds 6 DOF support, adaptive stiffness (dual updates) and new logic for collision handling.

The color loop is not fully parallel but block parallel, it becomes Gauss-Seidel when it switches between colors.

<img width="381" height="122" alt="Image" src="https://github.com/user-attachments/assets/f2c22a3e-b97b-457c-acca-482eebfbe3d2" />

There's more information about this in the [original paper](https://graphics.cs.utah.edu/research/projects/vbd/vbd-siggraph2024.pdf).

<img width="435" height="115" alt="Image" src="https://github.com/user-attachments/assets/66d59333-c436-46df-816a-88d1c2586da4" />
